import { themeType } from '../types/themeType';
import COLORS from './colors';

export const LIGHT: themeType = {
  PRIMARY: COLORS.CIAN.LIGHT,
  BACKGROUND: COLORS.WHITE,
  NAVIGATION: COLORS.CLEAR,
  TEXT: COLORS.DARK,
  DISABLED: COLORS.GREY.MEDIUM,
  CARD: COLORS.GREY.MEDIUM,
  ICONS: COLORS.DARK,
  DELETE: COLORS.RED.LIGHT,
  PLACEHOLDER: COLORS.GREY.DARK,
  ANGRY: { BACKGROUND: COLORS.RED.LIGHT, TEXT: COLORS.RED.DARK },
  FANTASTIC: { BACKGROUND: COLORS.YELLOW.LIGHT, TEXT: COLORS.YELLOW.DARK },
  GREAT: { BACKGROUND: COLORS.BLUE.LIGHT, TEXT: COLORS.BLUE.DARK },
  HAPPY: { BACKGROUND: COLORS.GREEN.LIGHT, TEXT: COLORS.GREEN.DARK },
  NEUTRAL: { BACKGROUND: COLORS.ORANGE.LIGHT, TEXT: COLORS.ORANGE.DARK },
  SAD: { BACKGROUND: COLORS.PINK.LIGHT, TEXT: COLORS.PINK.DARK },
  STRESSED: { BACKGROUND: COLORS.PURPLE.LIGHT, TEXT: COLORS.PURPLE.DARK },
};

export const DARK: themeType = {
  PRIMARY: COLORS.CIAN.DARK,
  BACKGROUND: COLORS.BLACK,
  NAVIGATION: COLORS.BLACK,
  TEXT: COLORS.GREY.LIGHT,
  DISABLED: COLORS.DARK,
  CARD: COLORS.DARK,
  ICONS: COLORS.GREY.LIGHT,
  DELETE: COLORS.RED.DARK,
  PLACEHOLDER: COLORS.GREY.DARK,
  ANGRY: { BACKGROUND: COLORS.RED.DARK, TEXT: COLORS.RED.LIGHT },
  FANTASTIC: { BACKGROUND: COLORS.YELLOW.DARK, TEXT: COLORS.YELLOW.LIGHT },
  GREAT: { BACKGROUND: COLORS.BLUE.DARK, TEXT: COLORS.BLUE.LIGHT },
  HAPPY: { BACKGROUND: COLORS.GREEN.DARK, TEXT: COLORS.GREEN.LIGHT },
  NEUTRAL: { BACKGROUND: COLORS.ORANGE.DARK, TEXT: COLORS.ORANGE.LIGHT },
  SAD: { BACKGROUND: COLORS.PINK.DARK, TEXT: COLORS.PINK.LIGHT },
  STRESSED: { BACKGROUND: COLORS.PURPLE.DARK, TEXT: COLORS.PURPLE.LIGHT },
};

const THEME = {
  DARK,
  LIGHT,
};

export const THEME_ENUM = {
  DARK: 0,
  LIGHT: 1,
};

export default THEME;
